### ISSUE TITLE
你好大哥

### ISSUE THREAD

**Issue by XwyFromCN** [realguoshuai/hadoop_study#9]
大哥，问个问题，我在本地Windows用java的jdbc连接kerberos管理的hive数据库
一直报连接超时，kbr5.conf如下
ip(123.123.123.123假的)是服务器的映射，ping不通，但是能telnet 10000端口
请问，你知道连接超时可能的原因吗

includedir /etc/krb5.conf.d/

[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 dns_lookup_realm = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 rdns = false
 default_realm = HADOOP.COM
#default_ccache_name = KEYRING:persistent:%{uid}
 udp_preference_limit = 1
 kdc_timeout = 30

[realms]
 HADOOP.COM = {
  kdc = 123.123.123.123
  admin_server = 123.123.123.123
 }

[domain_realm]
 .hadoop.com = HADOOP.COM
 hadoop.com = HADOOP.COM

**Comment by realguoshuai** [comment]
额  这段时间一直都用的git更新 没怎么关注issue 这么久了都 解决了吗 ?

**Comment by XwyFromCN** [comment]
感谢你的回复，问题已解决，还是ip和端口的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"郭帅"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月2日(星期四) 下午2:55
收件人:&nbsp;"realguoshuai/hadoop_study"<hadoop_study@noreply.github.com&gt;;
抄送:&nbsp;"为了明天"<451066429@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [realguoshuai/hadoop_study] 你好大哥 (#9)




额  这段时间一直都用的git更新 没怎么关注issue 这么久了都 解决了吗 ?
